### ISSUE TITLE
parsering enclosure

### ISSUE THREAD

**Issue by AMJ-7** [Stitch7/reader#1]
i have two types of "enclosure url" like this:

`<enclosure url="http://www.radiozerosix.fr/upload/podcasts/audios/5784338b042d41.79777284.mp3" type="audio/mpeg" length="5986913"/>
<enclosure url="http://www.radiozerosix.fr/upload/podcasts/photos/main/5784338b047468.88036252_mini.png" type="image/png" length="131302"/>`

How can how can i get the "enclosure url" with type "audio/mpeg" ?

`- (void)parser:(NSXMLParser *)parser didStartElement:(NSString *)elementName namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qName attributes:(NSDictionary *)attributeDict
{
    if ([elementName isEqualToString:@"item"]) {
        self.currentEntry = [[Entry alloc] init];
    } else if ([elementName isEqualToString:@"enclosure"]) {
        self.currentEntry.enclosureURL = [NSURL URLWithString:[attributeDict objectForKey:@"url" ] ];
    }
    self.currentString = nil;
}`

**Comment by aelzohry** [comment]
do another check for type as example to pick the right data that you want to save for later use

**Comment by AMJ-7** [comment]
this is my rss: http://zero-six.radiosite.fr/rss-feed-7
i can't code it ?!

**Comment by AMJ-7** [comment]
i found solve for this issue : 

`- (void)parser:(NSXMLParser *)parser didStartElement:(NSString *)elementName namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qName attributes:(NSDictionary *)attributeDict {
   if ([elementName isEqualToString:@"enclosure"]) {
        if ([attributeDict[@"type"] isEqualToString:@"audio/mpeg"]) {
                        self.currentEntry.enclosureURL = [NSURL URLWithString:attributeDict[@"url"]];
        }
    }
}`
